services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: tenant-farm-app
        container_name: tenant-farm-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./codes:/var/www/html
        networks:
            - tenant-farm-network

    web:
        image: nginx:alpine
        container_name: tenant-farm-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./codes:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - tenant-farm-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: tenant-farm-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-laravel}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - tenant-farm-network

networks:
    tenant-farm-network:
        driver: bridge

volumes:
    db_data:
